/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bet {
  'id' : bigint,
  'status' : BetStatus,
  'eventId' : bigint,
  'odds' : number,
  'user' : Principal,
  'stake' : number,
  'selection' : Selection,
  'placedAt' : bigint,
  'payout' : number,
}
export type BetStatus = { 'Won' : null } |
  { 'Lost' : null } |
  { 'Open' : null } |
  { 'Void' : null };
export interface Event {
  'id' : bigint,
  'status' : EventStatus,
  'teamA' : string,
  'teamB' : string,
  'title' : string,
  'oddsA' : number,
  'oddsB' : number,
  'oddsX' : number,
  'createdAt' : bigint,
  'sport' : Sport,
  'outcome' : EventOutcome,
}
export interface EventFilter {
  'status' : [] | [EventStatus],
  'sport' : [] | [Sport],
}
export type EventOutcome = { 'Draw' : null } |
  { 'None' : null } |
  { 'TeamA' : null } |
  { 'TeamB' : null };
export type EventStatus = { 'Live' : null } |
  { 'Closed' : null } |
  { 'Resolved' : null } |
  { 'Upcoming' : null };
export interface LeaderboardEntry {
  'user' : Principal,
  'totalWinnings' : number,
}
export type Selection = { 'Draw' : null } |
  { 'TeamA' : null } |
  { 'TeamB' : null };
export type Sport = { 'NFL' : null } |
  { 'Basketball' : null } |
  { 'Tennis' : null } |
  { 'Soccer' : null } |
  { 'Esports' : null };
export interface UserProfile { 'balance' : number }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminDeposit' : ActorMethod<[Principal, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEvent' : ActorMethod<
    [string, Sport, string, string, number, number, number],
    bigint
  >,
  'getAllBets' : ActorMethod<[], Array<Bet>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[bigint], Event>,
  'getEvents' : ActorMethod<[[] | [EventFilter]], Array<Event>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyBets' : ActorMethod<[], Array<Bet>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBet' : ActorMethod<[bigint, Selection, number], bigint>,
  'resolveEvent' : ActorMethod<[bigint, EventOutcome], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEventStatus' : ActorMethod<[bigint, EventStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];