/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Sport = IDL.Variant({
  'NFL' : IDL.Null,
  'Basketball' : IDL.Null,
  'Tennis' : IDL.Null,
  'Soccer' : IDL.Null,
  'Esports' : IDL.Null,
});
export const BetStatus = IDL.Variant({
  'Won' : IDL.Null,
  'Lost' : IDL.Null,
  'Open' : IDL.Null,
  'Void' : IDL.Null,
});
export const Selection = IDL.Variant({
  'Draw' : IDL.Null,
  'TeamA' : IDL.Null,
  'TeamB' : IDL.Null,
});
export const Bet = IDL.Record({
  'id' : IDL.Nat,
  'status' : BetStatus,
  'eventId' : IDL.Nat,
  'odds' : IDL.Float64,
  'user' : IDL.Principal,
  'stake' : IDL.Float64,
  'selection' : Selection,
  'placedAt' : IDL.Int,
  'payout' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'balance' : IDL.Float64 });
export const EventStatus = IDL.Variant({
  'Live' : IDL.Null,
  'Closed' : IDL.Null,
  'Resolved' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const EventOutcome = IDL.Variant({
  'Draw' : IDL.Null,
  'None' : IDL.Null,
  'TeamA' : IDL.Null,
  'TeamB' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'status' : EventStatus,
  'teamA' : IDL.Text,
  'teamB' : IDL.Text,
  'title' : IDL.Text,
  'oddsA' : IDL.Float64,
  'oddsB' : IDL.Float64,
  'oddsX' : IDL.Float64,
  'createdAt' : IDL.Int,
  'sport' : Sport,
  'outcome' : EventOutcome,
});
export const EventFilter = IDL.Record({
  'status' : IDL.Opt(EventStatus),
  'sport' : IDL.Opt(Sport),
});
export const LeaderboardEntry = IDL.Record({
  'user' : IDL.Principal,
  'totalWinnings' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminDeposit' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        Sport,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'getAllBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
  'getEvents' : IDL.Func([IDL.Opt(EventFilter)], [IDL.Vec(Event)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBet' : IDL.Func([IDL.Nat, Selection, IDL.Float64], [IDL.Nat], []),
  'resolveEvent' : IDL.Func([IDL.Nat, EventOutcome], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEventStatus' : IDL.Func([IDL.Nat, EventStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Sport = IDL.Variant({
    'NFL' : IDL.Null,
    'Basketball' : IDL.Null,
    'Tennis' : IDL.Null,
    'Soccer' : IDL.Null,
    'Esports' : IDL.Null,
  });
  const BetStatus = IDL.Variant({
    'Won' : IDL.Null,
    'Lost' : IDL.Null,
    'Open' : IDL.Null,
    'Void' : IDL.Null,
  });
  const Selection = IDL.Variant({
    'Draw' : IDL.Null,
    'TeamA' : IDL.Null,
    'TeamB' : IDL.Null,
  });
  const Bet = IDL.Record({
    'id' : IDL.Nat,
    'status' : BetStatus,
    'eventId' : IDL.Nat,
    'odds' : IDL.Float64,
    'user' : IDL.Principal,
    'stake' : IDL.Float64,
    'selection' : Selection,
    'placedAt' : IDL.Int,
    'payout' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'balance' : IDL.Float64 });
  const EventStatus = IDL.Variant({
    'Live' : IDL.Null,
    'Closed' : IDL.Null,
    'Resolved' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const EventOutcome = IDL.Variant({
    'Draw' : IDL.Null,
    'None' : IDL.Null,
    'TeamA' : IDL.Null,
    'TeamB' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'status' : EventStatus,
    'teamA' : IDL.Text,
    'teamB' : IDL.Text,
    'title' : IDL.Text,
    'oddsA' : IDL.Float64,
    'oddsB' : IDL.Float64,
    'oddsX' : IDL.Float64,
    'createdAt' : IDL.Int,
    'sport' : Sport,
    'outcome' : EventOutcome,
  });
  const EventFilter = IDL.Record({
    'status' : IDL.Opt(EventStatus),
    'sport' : IDL.Opt(Sport),
  });
  const LeaderboardEntry = IDL.Record({
    'user' : IDL.Principal,
    'totalWinnings' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminDeposit' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          Sport,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [Event], ['query']),
    'getEvents' : IDL.Func([IDL.Opt(EventFilter)], [IDL.Vec(Event)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyBets' : IDL.Func([], [IDL.Vec(Bet)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBet' : IDL.Func([IDL.Nat, Selection, IDL.Float64], [IDL.Nat], []),
    'resolveEvent' : IDL.Func([IDL.Nat, EventOutcome], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEventStatus' : IDL.Func([IDL.Nat, EventStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };