/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    user: Principal;
    totalWinnings: number;
}
export interface Bet {
    id: bigint;
    status: BetStatus;
    eventId: bigint;
    odds: number;
    user: Principal;
    stake: number;
    selection: Selection;
    placedAt: bigint;
    payout: number;
}
export interface Event {
    id: bigint;
    status: EventStatus;
    teamA: string;
    teamB: string;
    title: string;
    oddsA: number;
    oddsB: number;
    oddsX: number;
    createdAt: bigint;
    sport: Sport;
    outcome: EventOutcome;
}
export interface EventFilter {
    status?: EventStatus;
    sport?: Sport;
}
export interface UserProfile {
    balance: number;
}
export enum BetStatus {
    Won = "Won",
    Lost = "Lost",
    Open = "Open",
    Void = "Void"
}
export enum EventOutcome {
    Draw = "Draw",
    None = "None",
    TeamA = "TeamA",
    TeamB = "TeamB"
}
export enum EventStatus {
    Live = "Live",
    Closed = "Closed",
    Resolved = "Resolved",
    Upcoming = "Upcoming"
}
export enum Selection {
    Draw = "Draw",
    TeamA = "TeamA",
    TeamB = "TeamB"
}
export enum Sport {
    NFL = "NFL",
    Basketball = "Basketball",
    Tennis = "Tennis",
    Soccer = "Soccer",
    Esports = "Esports"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminDeposit(user: Principal, amount: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createEvent(title: string, sport: Sport, teamA: string, teamB: string, oddsA: number, oddsX: number, oddsB: number): Promise<bigint>;
    getAllBets(): Promise<Array<Bet>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEvent(eventId: bigint): Promise<Event>;
    getEvents(filter: EventFilter | null): Promise<Array<Event>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMyBets(): Promise<Array<Bet>>;
    getMyProfile(): Promise<UserProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    placeBet(eventId: bigint, selection: Selection, stake: number): Promise<bigint>;
    resolveEvent(eventId: bigint, outcome: EventOutcome): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEventStatus(eventId: bigint, status: EventStatus): Promise<void>;
}
import type { Bet as _Bet, BetStatus as _BetStatus, Event as _Event, EventFilter as _EventFilter, EventOutcome as _EventOutcome, EventStatus as _EventStatus, Selection as _Selection, Sport as _Sport, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminDeposit(arg0: Principal, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeposit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeposit(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: string, arg1: Sport, arg2: string, arg3: string, arg4: number, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, to_candid_Sport_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, to_candid_Sport_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async getAllBets(): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBets();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBets();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_Event_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_Event_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(arg0: EventFilter | null): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents(to_candid_opt_n23(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMyBets(): Promise<Array<Bet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBets();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBets();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeBet(arg0: bigint, arg1: Selection, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBet(arg0, to_candid_Selection_n29(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBet(arg0, to_candid_Selection_n29(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async resolveEvent(arg0: bigint, arg1: EventOutcome): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveEvent(arg0, to_candid_EventOutcome_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveEvent(arg0, to_candid_EventOutcome_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateEventStatus(arg0: bigint, arg1: EventStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEventStatus(arg0, to_candid_EventStatus_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEventStatus(arg0, to_candid_EventStatus_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BetStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BetStatus): BetStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Bet_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bet): Bet {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_EventOutcome_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventOutcome): EventOutcome {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Selection_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Selection): Selection {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Sport_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sport): Sport {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EventStatus;
    teamA: string;
    teamB: string;
    title: string;
    oddsA: number;
    oddsB: number;
    oddsX: number;
    createdAt: bigint;
    sport: _Sport;
    outcome: _EventOutcome;
}): {
    id: bigint;
    status: EventStatus;
    teamA: string;
    teamB: string;
    title: string;
    oddsA: number;
    oddsB: number;
    oddsX: number;
    createdAt: bigint;
    sport: Sport;
    outcome: EventOutcome;
} {
    return {
        id: value.id,
        status: from_candid_EventStatus_n17(_uploadFile, _downloadFile, value.status),
        teamA: value.teamA,
        teamB: value.teamB,
        title: value.title,
        oddsA: value.oddsA,
        oddsB: value.oddsB,
        oddsX: value.oddsX,
        createdAt: value.createdAt,
        sport: from_candid_Sport_n19(_uploadFile, _downloadFile, value.sport),
        outcome: from_candid_EventOutcome_n21(_uploadFile, _downloadFile, value.outcome)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BetStatus;
    eventId: bigint;
    odds: number;
    user: Principal;
    stake: number;
    selection: _Selection;
    placedAt: bigint;
    payout: number;
}): {
    id: bigint;
    status: BetStatus;
    eventId: bigint;
    odds: number;
    user: Principal;
    stake: number;
    selection: Selection;
    placedAt: bigint;
    payout: number;
} {
    return {
        id: value.id,
        status: from_candid_BetStatus_n8(_uploadFile, _downloadFile, value.status),
        eventId: value.eventId,
        odds: value.odds,
        user: value.user,
        stake: value.stake,
        selection: from_candid_Selection_n10(_uploadFile, _downloadFile, value.selection),
        placedAt: value.placedAt,
        payout: value.payout
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Draw: null;
} | {
    TeamA: null;
} | {
    TeamB: null;
}): Selection {
    return "Draw" in value ? Selection.Draw : "TeamA" in value ? Selection.TeamA : "TeamB" in value ? Selection.TeamB : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Live: null;
} | {
    Closed: null;
} | {
    Resolved: null;
} | {
    Upcoming: null;
}): EventStatus {
    return "Live" in value ? EventStatus.Live : "Closed" in value ? EventStatus.Closed : "Resolved" in value ? EventStatus.Resolved : "Upcoming" in value ? EventStatus.Upcoming : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    NFL: null;
} | {
    Basketball: null;
} | {
    Tennis: null;
} | {
    Soccer: null;
} | {
    Esports: null;
}): Sport {
    return "NFL" in value ? Sport.NFL : "Basketball" in value ? Sport.Basketball : "Tennis" in value ? Sport.Tennis : "Soccer" in value ? Sport.Soccer : "Esports" in value ? Sport.Esports : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Draw: null;
} | {
    None: null;
} | {
    TeamA: null;
} | {
    TeamB: null;
}): EventOutcome {
    return "Draw" in value ? EventOutcome.Draw : "None" in value ? EventOutcome.None : "TeamA" in value ? EventOutcome.TeamA : "TeamB" in value ? EventOutcome.TeamB : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Won: null;
} | {
    Lost: null;
} | {
    Open: null;
} | {
    Void: null;
}): BetStatus {
    return "Won" in value ? BetStatus.Won : "Lost" in value ? BetStatus.Lost : "Open" in value ? BetStatus.Open : "Void" in value ? BetStatus.Void : value;
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bet>): Array<Bet> {
    return value.map((x)=>from_candid_Bet_n6(_uploadFile, _downloadFile, x));
}
function to_candid_EventFilter_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventFilter): _EventFilter {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_EventOutcome_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventOutcome): _EventOutcome {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_EventStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): _EventStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_Selection_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Selection): _Selection {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_Sport_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): _Sport {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventFilter | null): [] | [_EventFilter] {
    return value === null ? candid_none() : candid_some(to_candid_EventFilter_n24(_uploadFile, _downloadFile, value));
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: EventStatus;
    sport?: Sport;
}): {
    status: [] | [_EventStatus];
    sport: [] | [_Sport];
} {
    return {
        status: value.status ? candid_some(to_candid_EventStatus_n26(_uploadFile, _downloadFile, value.status)) : candid_none(),
        sport: value.sport ? candid_some(to_candid_Sport_n3(_uploadFile, _downloadFile, value.sport)) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): {
    Live: null;
} | {
    Closed: null;
} | {
    Resolved: null;
} | {
    Upcoming: null;
} {
    return value == EventStatus.Live ? {
        Live: null
    } : value == EventStatus.Closed ? {
        Closed: null
    } : value == EventStatus.Resolved ? {
        Resolved: null
    } : value == EventStatus.Upcoming ? {
        Upcoming: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Selection): {
    Draw: null;
} | {
    TeamA: null;
} | {
    TeamB: null;
} {
    return value == Selection.Draw ? {
        Draw: null
    } : value == Selection.TeamA ? {
        TeamA: null
    } : value == Selection.TeamB ? {
        TeamB: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventOutcome): {
    Draw: null;
} | {
    None: null;
} | {
    TeamA: null;
} | {
    TeamB: null;
} {
    return value == EventOutcome.Draw ? {
        Draw: null
    } : value == EventOutcome.None ? {
        None: null
    } : value == EventOutcome.TeamA ? {
        TeamA: null
    } : value == EventOutcome.TeamB ? {
        TeamB: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): {
    NFL: null;
} | {
    Basketball: null;
} | {
    Tennis: null;
} | {
    Soccer: null;
} | {
    Esports: null;
} {
    return value == Sport.NFL ? {
        NFL: null
    } : value == Sport.Basketball ? {
        Basketball: null
    } : value == Sport.Tennis ? {
        Tennis: null
    } : value == Sport.Soccer ? {
        Soccer: null
    } : value == Sport.Esports ? {
        Esports: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
